<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_1_2</name>
   <tag></tag>
   <elementGuidId>26a58a61-a329-4a7b-94d8-d1bb3ae0f9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.control__element.icon__calenar > span.icon > svg > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(255,255,255)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>nonzero</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value> M 29 14 L 28 14 L 28 12 L 26 12 L 26 14 L 18 14 L 18 12 L 16 12 L 16 14 L 15 14 C 13.89 14 13.01 14.9 13.01 16 L 13 30 C 13 31.105 13.895 32 15 32 L 29 32 C 30.1 32 31 31.1 31 30 L 31 16 C 31 14.9 30.1 14 29 14 Z  M 29 30 L 15 30 L 15 19 L 29 19 L 29 30 Z  M 17 21 L 22 21 L 22 26 L 17 26 L 17 21 Z </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/main[@class=&quot;app__container&quot;]/div[@class=&quot;app__wrapper&quot;]/div[@class=&quot;app__content col-8&quot;]/div[@class=&quot;section__wrapper&quot;]/section[@class=&quot;section section__content&quot;]/div[@class=&quot;timeline__container&quot;]/div[@class=&quot;timeline__control&quot;]/div[1]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/span[@class=&quot;control__element icon__calenar&quot;]/span[@class=&quot;icon&quot;]/svg[1]/path[1]</value>
   </webElementProperties>
</WebElementEntity>
